### PR TITLE
Create opi_video_publishing_policy.md

### PR DESCRIPTION
**Pull request by glimchb**

### CODE REVIEW

**Review by pdp2shirts — COMMENTED** [review]
Is the intent to have TSC review presentation prior to being presented at an event, or to review an already presented presentation/recording prior to posting to our various distribution platforms (YouTube, GitHub,etc.)

**Comment by glimchb** [comment]
> Is the intent to have TSC review presentation prior to being presented at an event, or to review an already presented presentation/recording prior to posting to our various distribution platforms (YouTube, GitHub,etc.)

I think the intent for TSC review any presentation prior to being presented or posted publicly

**Comment by mestery** [comment]
> > Is the intent to have TSC review presentation prior to being presented at an event, or to review an already presented presentation/recording prior to posting to our various distribution platforms (YouTube, GitHub,etc.)
> 
> I think the intent for TSC review any presentation prior to being presented or posted publicly

How are we going to do that? I can present on OPI if I'm representing myself and not OPI, for example.

I thought the intent of this was to review *videos published to the OPI YouTube channel*.

**Comment by glimchb** [comment]
> > > Is the intent to have TSC review presentation prior to being presented at an event, or to review an already presented presentation/recording prior to posting to our various distribution platforms (YouTube, GitHub,etc.)
> > 
> > 
> > I think the intent for TSC review any presentation prior to being presented or posted publicly
> 
> How are we going to do that? I can present on OPI if I'm representing myself and not OPI, for example.
> 
> I thought the intent of this was to review _videos published to the OPI YouTube channel_.

the title is `Video and Presentation approval Process`

**Comment by mestery** [comment]
> > > > Is the intent to have TSC review presentation prior to being presented at an event, or to review an already presented presentation/recording prior to posting to our various distribution platforms (YouTube, GitHub,etc.)
> > > 
> > > 
> > > I think the intent for TSC review any presentation prior to being presented or posted publicly
> > 
> > 
> > How are we going to do that? I can present on OPI if I'm representing myself and not OPI, for example.
> > I thought the intent of this was to review _videos published to the OPI YouTube channel_.
> 
> the title is `Video and Presentation approval Process`

Having the TSC approve presentations *when people are representing OPI* seems ok, but massively heavyweight. But we can't prevent people *who represent themselves or their company* from talking about OPI. So this seems peculiar to me.

**Comment by timmichels** [comment]
I think the idea is to have a set of "approved" slides or even decks that can be used over and over again for OPI presentations so that we have a uniformity and consistency of our OPI message.  These slides should be available for ad hoc use by any OPI member for private/corporate presentations with no further OPI involvement.  Only new material needs to reviewed which should be as simple a process as possible.  Mostly there are no arguments (yet!) about the content.  We just want consistency and some oversight of the OPI message when delivered by an OPI representative.  I agree with Kyle that individuals presenting as corporate reps (not OPI), can and will do whatever they please.  But if they are enabled by OPI approved materials, even there we will see some consistency emerge.

**Comment by jlwhite** [comment]
This review proposal is for public, OPI branded, OPI delivered, and OPI hosted presentations and videos. SNIA does this for content it publishes for example. 

If a company presents how they will use or leverage OPI even publicly that is up to the company. We can't and shouldn't control what is presented. If a company or person gives a private presentation there is no control unless they are speaking on behalf of OPI or representing and OPI position. For example Dell talks about FMDS NVMe-oF work all the time but not about the structure or plans for future standards, that is controlled and restricted until the standards are published and for the NVMe.org board to define and present. 

The central repository is a related concept of approved technical slides on OPI that anyone can pull from to create presentations as needed for both public and private use. This is useful value add so we have consistency and make building useful presentations simpler.

**Comment by jlwhite** [comment]
I don't think the copied text in this .md file is the fully realized process. The point was to get this discussion going.

**Comment by venkat-pullela-keys** [comment]
It is important to have a little bit of oversight till certain major multi-vendor issues are resolved. For example, if IPDK is the OPI or do we have OPI APIs that map to multiple vendor specific interfaces. We may even need an FAQ to cover some issues. We have to keep it up to date. We may have to mandate that any custom presentation at least conform to the FAQs if they use OPI logo and references to prevent any deviation in messaging.

**Comment by glimchb** [comment]
@jlwhite created new pull request https://github.com/opiproject/opi/pull/30

**Pull request closed without merging**
