### PR TITLE
Create Open_Programmable_Infrastructure_Funding_Charter_final.md

### PR DESCRIPTION
**Pull request by pdp2shirts**
Creating a draft for review as proper markdown etc. 
Would like to wait until LF has chimed in on non-content text changes 
before merging
Signed-off-by: Paul Pindell <ppindell@gmail.com>

### CODE REVIEW

**Comment by pdp2shirts** [comment]
@opiproject/opi-maintainers Sridhar indicated in Slack that the formatting differences are ok when using GH. I've set the to ready for review.

**Comment by pdp2shirts** [comment]
@glimchb @mestery Boris has reviewed this. Kyle can you review and let me know if this is merge worthy.

**Review by mestery — APPROVED** [review]
I'm actually fine with this. I did not read it word for word, but I assume that you translated it directly from the PDF file @pdp2shirts. Thanks!

**Comment by pdp2shirts** [comment]
Ping @opiproject/opi-maintainers Can we get a second maintainer approval and have this merged. it is not available anywhere publicly at this point.
Paul

**Comment by mestery** [comment]
> Ping @opiproject/opi-maintainers Can we get a second maintainer approval and have this merged. it is not available anywhere publicly at this point.
> Paul

The PDF has been available for months here: https://github.com/opiproject/opi/blob/main/Open_Programmable_Infrastructure_Technical_Charter_Final-06-9-2022.pdf

**Review by seroyer — APPROVED** [review]

**Pull request merged**
