### PR TITLE
Abstraction across DPUs & IPUs

### PR DESCRIPTION
**Pull request by dandaly**

### CODE REVIEW

**Comment by dandaly** [comment]
Looks like the linter got hung up on another file

**Review by glimchb — CHANGES_REQUESTED** [review]
personally I don't like us introducing new term for DPU which nobody knows : `OPN (Open Programmable Node)`
let's hear from others

**Comment by dandaly** [comment]
> personally I don't like us introducing new term for DPU which nobody knows : `OPN (Open Programmable Node)` let's hear from others

This isn't messing with any existing terminology or renaming anything, it is an umbrella term across different node implementations (including form factors, hopefully someday). DPU is not a good name for the platform, and it isn't implementation agnostic.  This term also nicely summarizes what OPI is trying to accomplish.

**Comment by glimchb** [comment]
> This isn't messing with any existing terminology or renaming anything, it is an umbrella term across different node implementations (including form factors, hopefully someday). DPU is not a good name for the platform, and it isn't implementation agnostic. This term also nicely summarizes what OPI is trying to accomplish.

GPU is also not the best name, but I'm not aware of anybody trying to rename it...

**Comment by pdp2shirts** [comment]
I, too, am not a fan of creating a new name and acronym for a DPU. 
If I were king I would say we simply call them DPUs. This is what I hear from most of my interactions with industry folks. The conversation is something like: "a device like this is called a Data Processing Unit (DPU)...unless you are Intel, who for some reason had their marketers call them IPUs (Infrastructure Processing Units)...." 
But I get the need to be sensitive to Intel's naming convention and for our community to be open and not intentionally or unintentionally exclude Intel. We should be agnostic to the political naming battle that happens in the market. 
So my (I'm not king) vote would be that we stick with "DPU/IPU" in an effort to be agnostic. Until such time if ever that Intel drops the IPU name we should stick with "DPU/IPU". This would be how the devices OPI is concerned with are designated in all marketing, website, presentation, etc. documentation. 
I would be amenable to having comments in code make use of "DPU/IPU" and have the code itself use the simplified and shortened form of DPU to avoid using the "/" in non-comment code blocks, as long as the comments make it explicit that when we mention "DPU" in a code block we're referring to a "DPU/IPU" 
As such I do not approve of the creation of the OPN (Open Programmable Node) terminology suggested in the PR.

**Comment by dandaly** [comment]
> I, too, am not a fan of creating a new name and acronym for a DPU.

Why do you say that this is creating a new name and acronym for a DPU?  A DPU is a chip. This definition is for the node or the system that is the whole bag of chips.

**Comment by jlwhite** [comment]
Most of the industry uses DPU to mean both the piece of silicon and the card with the distinction coming from context where that distinction is important. 

After some thought, for marketing and presentations I'm fine with retaining DPU/IPU for OPI. SNIA and others will use DPU but there should be no confusion so no issues. We started with this approach.

As far as the proposal goes, I think OPN used in this context will be adding yet another term for the DPU/IPU/SmartNIC/xPU class of devices especially as depicted in the diagram. To suggest that this (OPN) umbrella term will be generally acceptable while DPU is not, implies that we can use OPN in place of DPU/IPU... I don't think it would work that way. 

We already have a term in use in the code that attempted to sidestep the terminology discussion: xPU or xpu, It is no worse than OPN for the code and we have already been using it (49 files). Substitute 'D' or 'I' or even 'S' (for Smart :) ) for 'x' as needed. DPU is used in 196 files but about 1/3 of those references are in documents and proposals from member companies.  Another 1/3 are in the DPU/IPU context for documentation or comments. Of what's left a block of files are for vendor interface code where using what the vendor prefers is acceptable.

**Comment by jlwhite** [comment]
The OPN properties listed out in the proposal do conform to what OPI has been using as top level tenets. No arguments on the function just the form.

**Comment by dandaly** [comment]
> After some thought, for marketing and presentations I'm fine with retaining DPU/IPU for OPI. SNIA and others will use DPU but there should be no confusion so no issues. We started with this approach.
> We already have a term in use in the code that attempted to sidestep the terminology discussion: xPU or xpu

I am going to put this into the document as an alternative- retain the DPU/IPU naming and leverage xPU for brevity, including code.

**Comment by dandaly** [comment]
I added this to the end, I called it an Alternative but I'd like to lead with it in the TSC meeting. Hard to pass up solving all of our problems with a TCAM:

OPI uses the term DPU/IPU to represent the entire class of DPU/IPU-like devices, and can refer to either the system containing a DPU/IPU-like device or to the device itself. In cases where brevity is needed (especially in code), OPI uses the term xPU.

**Comment by jlwhite** [comment]
xPU or xpu should only be used in the code itself where absolutely needed to make a script or function/module name completely clear. Nearly all of the definitions and code should not need this term. The more we contain it the better.

**Comment by pdp2shirts** [comment]
Agree with Joe. I'm ok with xPU in code in as few places as necessary.

**Comment by dandaly** [comment]
Closing this, opened up #51

**Pull request closed without merging**
