### PR TITLE
Update publishing_policy.md

### PR DESCRIPTION
**Pull request by pdp2shirts**
updated link to Youtube channel
Signed-off-by: Paul Pindell <ppindell@gmail.com>

### CODE REVIEW

**Comment by pdp2shirts** [comment]
@opiproject/opi-maintainers Simple PR to update the link to the YouTube location for our videos.

**Comment by artek-koltun** [comment]
@pdp2shirts please adjust the commit header according to the [conventioanl commit format](https://www.conventionalcommits.org/en/v1.0.0/)
```
config: ./.github/commitlintrc.yml
22c1418: Update publishing_policy.md

updated link to Youtube channel
Signed-off-by: Paul Pindell <ppindell@gmail.com>

Signed-off-by: Paul Pindell <ppindell@gmail.com>
Error: ✖ subject may not be empty
Error: ✖ type may not be empty
Error: commitlint **failed**
```

Maybe `fix: update publishing_policy.md`?

**Comment by pdp2shirts** [comment]
@artek-koltun I'm not certain what you are asking for here. I'm not seeing where this should be done. there was no subject field that I remember when I created this PR.

**Comment by artek-koltun** [comment]
@pdp2shirts You need to update the commit message, so it is compliant with [commitlint](https://www.conventionalcommits.org/en/v1.0.0/) rules.
Here's what you need to do:
* Open up your terminal and navigate to the `opi` repo.
* Run `git commit --amend`. This will allow to edit the commit message in your text editor.
* Edit the commit message to follow the conventional commit format. Here's an example of how you could rephrase it:
```
fix: update publishing_policy.md

updated link to Youtube channel

Signed-off-by: Paul Pindell <ppindell@gmail.com>
```
* Save and close the editor. This will update the commit message.
* Force push the amended commit with `git push --force`.

**Review by glimchb — APPROVED** [review]
content lgtm
failed checker needs fixing

**Comment by artek-koltun** [comment]
@pdp2shirts Would you like to update the commit message yourself, or would you prefer if I handle it?

**Comment by pdp2shirts** [comment]
I started down path to update it. But I had only used the web gui to make this PR. So I don’t have on my system the commit to be able to amend it. And I do not see an option in web gui to amend the commit. I would take instruction on how to do this, but also understand it might be simpler and faster for you to update the commit message. Paul On Jan 11, 2024, at 1:38 AM, Artek Koltun ***@***.***> wrote:﻿
@pdp2shirts Would you like to update the commit message yourself, or would you prefer if I handle it?

**Comment by artek-koltun** [comment]
> I started down path to update it. But I had only used the web gui to make this PR. So I don’t have on my system the commit to be able to amend it. And I do not see an option in web gui to amend the commit. I would take instruction on how to do this, but also understand it might be simpler and faster for you to update the commit message. Paul On Jan 11, 2024, at 1:38 AM, Artek Koltun ***@***.***> wrote:﻿ @pdp2shirts Would you like to update the commit message yourself, or would you prefer if I handle it? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

@pdp2shirts please see https://github.com/opiproject/opi/pull/79

**Comment by pdp2shirts** [comment]
Closing as #79 covers this.

**Pull request closed without merging**
