### PR TITLE
Remove Kyle as maintainer

### PR DESCRIPTION
**Pull request by mestery**
End of an era.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Review by seroyer — APPROVED** [review]
;(

**Review by glimchb — APPROVED** [review]
:-( thanks @mestery for all the work

**Comment by glimchb** [comment]
maybe we can add @mestery to `Core Maintainers Emeritus` ? @seroyer

**Comment by seroyer** [comment]
> maybe we can add @mestery to `Core Maintainers Emeritus` ? @seroyer

100%

**Comment by mestery** [comment]
> maybe we can add @mestery to `Core Maintainers Emeritus` ? @seroyer

I will update!

**Comment by stolsma** [comment]
Good luck @mestery, was nice working with you!!👍

**Pull request merged**
