### PR TITLE
Markdown lint fixes

### PR DESCRIPTION
**Pull request by mestery**
Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Review by glimchb — COMMENTED** [review]
did you mean to remove the tech charter ?

**Comment by mestery** [comment]
> did you mean to remove the tech charter ?

I did, because that was the example we used to form the official charter which all the funding companies signed. It's no longer relevant because it's not the technical charter we're using (though the one the funding members signed has many elements from this one).

**Comment by glimchb** [comment]
> > did you mean to remove the tech charter ?
> 
> I did, because that was the example we used to form the official charter which all the funding companies signed. It's no longer relevant because it's not the technical charter we're using (though the one the funding members signed has many elements from this one).

thanks, for clarifications. next time split it in separate commit

**Review by glimchb — APPROVED** [review]
lgtm

**Comment by mestery** [comment]
> > > did you mean to remove the tech charter ?
> > 
> > 
> > I did, because that was the example we used to form the official charter which all the funding companies signed. It's no longer relevant because it's not the technical charter we're using (though the one the funding members signed has many elements from this one).
> 
> thanks, for clarifications. next time split it in separate commit

I'm trying to be energy efficient with CI runs ;)

**Pull request merged**
