### PR TITLE
Remove disbanded subgroups

### PR DESCRIPTION
**Pull request by glimchb**
Since moving to Linux Foundation, those groups were wither closed or combined
This pull requests aligns to the current project status

### CODE REVIEW

**Review by mestery — APPROVED** [review]
YES!

**Review by seroyer — APPROVED** [review]

**Review by sandersms — APPROVED** [review]
Good with the cleanup.

**Review by pdp2shirts — APPROVED** [review]
At this point only change I'd make is to let folks know the outreach and events committee is being formed and a call is "to be scheduled" and I have a question as to whether we state  that the new outreach group is merging the functionality of the disbanded groups. Do we want to add that, or "just the facts, Maam"

**Comment by glimchb** [comment]
> At this point only change I'd make is to let folks know the outreach and events committee is being formed and a call is "to be scheduled" and I have a question as to whether we state that the new outreach group is merging the functionality of the disbanded groups. Do we want to add that, or "just the facts, Maam"

I was thinking doing that, but notice this new group is already in the document and this PR is not removing that.
Let me know if you want some extra wording, I'm ok with anything

**Pull request merged**
