### PR TITLE
Add TSC Charter

### PR DESCRIPTION
**Pull request by mestery**
Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
yes

**Review by seroyer — APPROVED** [review]

**Review by sandersms — APPROVED** [review]

**Review by pdp2shirts — COMMENTED** [review]
This is the one that was signed by all members using the LF portal back in June correct? Does the one Sridhar posted in Slack need to be voted on during the first TSC meeting, or was that done via email already?

**Review by glimchb — APPROVED** [review]
lgtm

**Comment by mestery** [comment]
> This is the one that was signed by all members using the LF portal back in June correct? Does the one Sridhar posted in Slack need to be voted on during the first TSC meeting, or was that done via email already?

This new one was already approved by the TSC in a private vote.

**Pull request merged**
