### PR TITLE
reorg: Move files around

### LINKED ISSUE #40: Reorganize the files in the OPI repository
This issue will track the work to move things around in the OPI repository. This includes moving all policies into the appropriate directory.

### PR DESCRIPTION
**Pull request by mestery**
Move policy and procedure documents into the Policy folder. Adjust links where appropriate.

Closes #40

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
I want to remove the GOALS.md and GOALS_TO_GROUPS.md files as well as they are not really relevant anymore. Thoughts on adding that to this PR?

**Review by glimchb — APPROVED** [review]
lgtm

**Comment by mestery** [comment]
> lgtm

Are you ok if I wipe the two goals files out as well?

**Comment by glimchb** [comment]
> > lgtm
> 
> Are you ok if I wipe the two goals files out as well?

separate PR please

**Review by seroyer — APPROVED** [review]

**Pull request merged**
