### PR TITLE
Per the outreach team, global replace of "DPU/IPU" --> "D/IPU"

### PR DESCRIPTION
**Pull request by capveg-intel**
Actual implementation was:

 find . -type f | xargs perl -p -i -e 's/DPU\/IPU/D\/IPU/'

So this may have missed somethings, but looks like it got a lot.

### CODE REVIEW

**Review by pdp2shirts — COMMENTED** [review]
I do not think this is what the outreach committee intended here. The discussion was about changing from referencing xPU to DPU/IPU. D/IPU was not discussed in the outreach meeting. I saw some discussion on slack but I am of opinion that this should remain DPU/IPU. The change that needs to be made is to find instances of "xPU" and substitute in "DPU/IPU".

**Comment by yanfisher** [comment]
I have already stated this on Slack and just getting around to doing it here - we have not discussed shortening the DPU/IPU abbreviation at all, as Paul stated before. Additional points made about use of "/" character in code and file names are valid concerns and we should address them separately. Until then, I suggest that this PR is closed.

**Review by timmichels — CHANGES_REQUESTED** [review]
I agree with Paul and Yan.  We are not moving off of DPU/IPU.  These changes are not approved and the PR should be closed.

**Comment by capveg-intel** [comment]
Apologies - I misunderstood the level of consensus around this.  Closing the PR and we can discuss more.

**Comment by pdp2shirts** [comment]
Rob, 

I think a PR that searched for xPU and replaced with DPU/IPU would be inline with the intention of the Outreach committee. 

Paul

**Pull request closed without merging**
